---
# tasks file for roles/webservers

- name: update all packages to the latest version
  apt: 
    upgrade: dist
    update_cache: yes

- name: install apache webserver
  apt: 
    name: apache2 
    state: present

- name: delete original index.html file
  file: path=/var/www/html/index.html state=absent

- name: create new index.html file
  lineinfile:
    create: yes
    path: /var/www/html/index.html
    line: <html>{{ "Hola mundo"|replace("mundo", "from ") }}server3</html>
  when: server_number == 5
  notify: start apache

- name: create new index.html file
  lineinfile:
    create: yes
    path: /var/www/html/index.html
    line: <html>{{ "Hola mundo"|replace("mundo", "from ") }}server3</html>
  when: server_number == 3
  notify: start apache

- name: start apache
  service: name=apache2 state=started