# Challenge3 - playbook that updates packages, installs apache, copy index from github into /var/www..... directory, handler called and starts apache
---
  - hosts: webservers
    become: true
    tasks:
      - name: Update packages to the latest versions
        apt:
          upgrade: dist
          update_cache: yes

      - name: Install Apache
        apt:
          name: apache2
          state: present

      - name: Delete original index.html file
        file:
          path: /var/www/html/index.html
          state: absent

      - name: Create new folder for GitHub
        file:
          path: /tmp/github
          state: directory

      - name: Copy GitHub repository to the new folder
        git:
          repo: https://github.com/agomez94/ansible101.git
          dest: /tmp/github/ansible101
          force: yes

      - name: Copy index.html from GitHub repository to /var/www/html/
        copy:
          src: /tmp/github/ansible101/index.html
          dest: /var/www/html/index.html
          owner: root
          group: root
          mode: 0644
          remote_src: yes

    handlers:
      - name: Start Apache service
        service:
          name: apache2
          state: started