# copy and place file on host
---
- name: Deploy index.html
  hosts: webservers
  become: true

  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Apache webserver
      apt:
        name: apache2
        state: present

    - name: Delete original index.html file
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy local index.html to the remote hosts
      copy:
        src: /wsl.localhost/Ubuntu/home/devops/ansible/ansible_playbooks/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
        remote_src: yes

    - name: Start Apache service
      service:
        name: apache2
        state: started