# setup webserver
---
  - hosts: webservers
    become: true
    tasks:
      - name: install apache webserver
        apt: 
          name: apache2 
          state: present

      - name: delete original index.html file
        file: path=/var/www/html/index.html state=absent