# setup webserver
---
  - hosts: webservers
    become: true
    tasks:
      - name: update all packages to the latest version
        apt: 
          upgrade: dist
          update_cache: yes